version: '3'
services:
  cible_1:
    image: test/vuln-ubuntu
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      lan_net:
        ipv4_address: 172.50.0.2
    command: sh -c 'ip route replace default via 172.50.0.250 && tail -f /dev/null'
  attacker_1:
    image: test/kali_attack
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      wan_net:
        ipv4_address: 172.60.0.2
    command: sh -c 'ip route replace default via 172.60.0.250 && tail -f /dev/null'
  gateway:
    image: test/gateway
    networks:
      lan_net:
        ipv4_address: 172.50.0.250
      wan_net:
        ipv4_address: 172.60.0.250
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
networks:
  lan_net:
    driver: bridge
    ipam:
      config:
       - subnet: 172.50.0.0/24
  wan_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/24
